# scripts to run before `bun run`ning a file or script
# useful for registering plugins

logLevel = "debug" # "debug" | "warn" | "error"

[install]
optional = true
dev = true
peer = false
auto = "auto"